name: Integrate

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        name: Build

        runs-on: ubuntu-latest

        steps:
            - run: echo 'A dummy integration to trigger Dependabot'
