name: publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/lukasleitsch/hetzner-gitlab-runner:latest
        docker push ghcr.io/lukasleitsch/hetzner-gitlab-runner:latest
